import React, { useState } from "react";
import { Link } from "react-router-dom";
import jsPDF from "jspdf"; // ✅ new line
import "../EncryptTech/EncryptTech.css";
import caesarBg from "../assets/bg2.jpg";

const CaesarEncrypt = () => {
  const [message, setMessage] = useState("");
  const [shift, setShift] = useState("");
  const [steps, setSteps] = useState([]);
  const [finalResult, setFinalResult] = useState("");

  const handleEncrypt = (e) => {
    e.preventDefault();
    const shiftAmount = parseInt(shift);
    if (isNaN(shiftAmount)) {
      setFinalResult("⚠️ Please enter a valid number for shift.");
      return;
    }

    let result = "";
    let explanationSteps = [];

    const upperMessage = message.toUpperCase();

    for (let i = 0; i < upperMessage.length; i++) {
      const char = upperMessage[i];

      if (char >= "A" && char <= "Z") {
        const originalPos = char.charCodeAt(0) - 65;
        const newPos = (originalPos + shiftAmount) % 26;
        const newChar = String.fromCharCode(newPos + 65);
        result += newChar;

        explanationSteps.push({
          id: i + 1,
          content: `Step ${
            i + 1
          }: The letter "${char}" is at position ${originalPos} in the alphabet.
          We add the shift value (${shiftAmount}): ${originalPos} + ${shiftAmount} = ${
            originalPos + shiftAmount
          }.
          After taking modulo 26: (${
            originalPos + shiftAmount
          } % 26 = ${newPos}),
          we get new position ${newPos}, which is "${newChar}".`,
        });
      } else {
        result += char;
        explanationSteps.push({
          id: i + 1,
          content: `Step ${
            i + 1
          }: The character "${char}" is not a letter, so we keep it unchanged.`,
        });
      }
    }

    setFinalResult(result);
    setSteps(explanationSteps);
  };

  // ✅ Generate PDF function
  // ✅ Generate Stylish / Trendy PDF
  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      const pageHeight = doc.internal.pageSize.height;
      const pad = 20;
      let y = 24;
      const lineGap = 8;
      const sectionGap = 14;

      // helpers
      const write = (txt, size = 11, color = [0, 0, 0]) => {
        doc.setFontSize(size);
        doc.setTextColor(...color);
        const lines = doc.splitTextToSize(txt, 170);
        lines.forEach((line) => {
          if (y > pageHeight - 30) {
            doc.addPage();
            y = 24;
          }
          doc.text(line, pad, y);
          y += lineGap;
        });
      };

      const writeSectionTitle = (txt) => {
        if (y + 10 > pageHeight - 20) {
          doc.addPage();
          y = 24;
        }
        doc.setFontSize(14);
        doc.setTextColor(17, 122, 101); // teal
        doc.text(txt, pad, y);
        y += sectionGap;
        doc.setDrawColor(17, 122, 101);
        doc.setLineWidth(0.5);
        doc.line(pad, y - 7, 190 - pad, y - 7);
      };

      // -------- Header Card --------
      doc.setDrawColor(46, 134, 193);
      doc.setFillColor(240, 248, 255);
      doc.roundedRect(pad - 5, y - 14, 170, 20, 3, 3, "F");
      doc.setFontSize(16);
      doc.setTextColor(46, 134, 193);
      doc.setFont("helvetica", "bold");
      doc.text(" Caesar Cipher — Encryption Walkthrough", pad, y);
      y += 24;

      // -------- Message + Key --------
      writeSectionTitle(" Input Details");
      write(`Original Message: ${message.toUpperCase()}`);
      write(`Shift Key: ${shift}`);

      // -------- Steps --------
      writeSectionTitle(" Step-by-Step Process");
      steps.forEach((step, index) => {
        const text = `${index + 1}. ${step.content}`;
        doc.setFontSize(11);
        doc.setTextColor(52, 73, 94);
        const split = doc.splitTextToSize(text, 170);
        split.forEach((line) => {
          if (y > pageHeight - 30) {
            doc.addPage();
            y = 24;
          }
          doc.text(line, pad, y);
          y += lineGap;
        });
        y += 4;
      });

      // -------- Final Result --------
      writeSectionTitle(" Final Encrypted Message");
      doc.setFont("courier", "bold");
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text(finalResult || "—", pad, y + 6);
      y += 20;

      // -------- Footer --------
      if (y + 16 > pageHeight) {
        doc.addPage();
        y = 24;
      }
      doc.setFontSize(9);
      doc.setTextColor(120, 120, 120);
      doc.text(
        "Generated by RagaCrypt • Caesar Cipher (Classic Crypto )",
        pad,
        pageHeight - 10
      );

      doc.save("CaesarCipher.pdf");
    } catch (err) {
      console.error(err);
      alert("PDF generation failed. Check console for details.");
    }
  };

  return (
    <div className="cipher-page">
      <div
        className="cipher-bg"
        style={{ backgroundImage: `url(${caesarBg})` }}
      ></div>
      <div className="cipher-overlay"></div>

      <div
        className={`cipher-content-wrapper ${finalResult ? "show-output" : ""}`}
      >
        {/* Left Input Section */}
        <div className="left-section">
          <div className="cipher-content">
            <h1>🔐 Caesar Cipher Encryption</h1>
            <p>
              The Caesar Cipher is a very simple way to hide a message. It works
              by shifting every letter in your message forward by a fixed
              number. For example, with a shift of 3: A becomes D, B becomes E,
              etc.
            </p>

            <form onSubmit={handleEncrypt} className="cipher-form">
              <input
                type="text"
                placeholder="Enter Plaintext"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                required
              />
              <input
                type="number"
                placeholder="Enter Shift Key (e.g. 3)"
                value={shift}
                onChange={(e) => setShift(e.target.value)}
                required
              />
              <button type="submit">Encrypt Message</button>
            </form>

            <section className="explanation">
              <h3>📚 How It Works</h3>
              <p>
                Each letter is moved forward by the number you choose (called
                the shift key). After 'Z', we start again from 'A'. Any spaces
                or punctuation are not changed.
              </p>
              <p>
                For example, with a shift of 3:
                <br />
                <code>HELLO → KHOOR</code>
              </p>
            </section>

            <div className="next-technique">
              <p>➡️ Ready for the next cipher?</p>
              <Link to="/encrypt/vigenere" className="next-link">
                Try Vigenère Cipher →
              </Link>
            </div>
          </div>
        </div>

        {/* Right Output Section */}
        {finalResult && (
          <div className="right-section white-output-box">
            <h2>🔏 Encrypted Output</h2>
            <p>
              <strong>Original Message:</strong> {message.toUpperCase()}
            </p>
            <p>
              <strong>Shift Key:</strong> {shift}
            </p>

            <h3>🧠 Step-by-Step Explanation</h3>
            <ul className="step-list">
              {steps.map((step) => (
                <li key={step.id}>{step.content}</li>
              ))}
            </ul>

            <h3>✅ Final Encrypted Message:</h3>
            <div className="final-encryption-box">{finalResult}</div>
            <button onClick={handleDownloadPDF} className="pdf-btn">
              📄 Download PDF
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default CaesarEncrypt;
